### ISSUE TITLE
Smoke detector not recognized

### ISSUE THREAD

**Issue by DomiStyle** [gluap/pyduofern#18]
I got one of the Duofern smoke detectors (ER10018992 and 32001664) for testing and it doesn't seem to be recognized. The IDs are correctly defined in the definitions.py from what I can see.

Smoke detector: https://github.com/gluap/pyduofern/blob/master/pyduofern/definitions.py#L55

Start smoke: https://github.com/gluap/pyduofern/blob/master/pyduofern/definitions.py#L76
End smoke: https://github.com/gluap/pyduofern/blob/master/pyduofern/definitions.py#L77

Pairing:
```
homeassistant_1  | 2020-08-20 11:53:24 WARNING (SyncWorker_37) [custom_components.duofern] start pairing
homeassistant_1  | 2020-08-20 11:53:24 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] sending 04000000000000000000000000000000000000000000 from write queue, 0 msgs left in queue
homeassistant_1  | 2020-08-20 11:53:32 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] got pairing reply
homeassistant_1  | 2020-08-20 11:53:32 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py] detected unknown device, ID=ab49b6
homeassistant_1  | 2020-08-20 11:53:32 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py] DUOFERN device paired, ID ab49b6
homeassistant_1  | 2020-08-20 11:53:32 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] paired new device 40535c
homeassistant_1  | 2020-08-20 11:53:32 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] paired new device 40bb37
homeassistant_1  | 2020-08-20 11:53:32 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] paired new device ab49b6
homeassistant_1  | 2020-08-20 11:53:54 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] sending 05000000000000000000000000000000000000000000 from write queue, 1 msgs left in queue
homeassistant_1  | 2020-08-20 11:53:54 INFO (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] sending 05000000000000000000000000000000000000000000 from write queue, 0 msgs left in queue
```

Test alarm:
```
homeassistant_1  | 2020-08-20 12:11:38 WARNING (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py] unknown message 0fff071e0100010000000000100002ab49b66f8d1c00
homeassistant_1  | 2020-08-20 12:11:38 ERROR (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] '071e'
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 595, in run
homeassistant_1  |     self.process_message(in_data)
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 227, in process_message
homeassistant_1  |     self.duofern_parser.parse(message)
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py", line 562, in parse
homeassistant_1  |     chan = msg[sensorMsg[id]['chan'] * 2 + 2:sensorMsg[id]['chan'] * 2 + 4]
homeassistant_1  | KeyError: '071e'
homeassistant_1  | 2020-08-20 12:12:24 WARNING (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py] unknown message 0fff071f0100010000000000100002ab49b66f8d1c00
homeassistant_1  | 2020-08-20 12:12:24 ERROR (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] '071f'
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 595, in run
homeassistant_1  |     self.process_message(in_data)
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 227, in process_message
homeassistant_1  |     self.duofern_parser.parse(message)
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py", line 562, in parse
homeassistant_1  |     chan = msg[sensorMsg[id]['chan'] * 2 + 2:sensorMsg[id]['chan'] * 2 + 4]
homeassistant_1  | KeyError: '071f'
```

Might just be looking for lowercase 071e and 071f but they are uppercase in definitions.py.

**Comment by gluap** [comment]
@DomiStyle Feel free to speak up if the case change alone does not fix it. Be aware that this code path is untested - myself and other users only use this for roller shutters so there is not much experience with other features.

Also be aware that to use the new version you need to also touch the homeassistant custom component (because it depends on a hard-wired version of pyduofern per homeassistant conventions).

**Comment by DomiStyle** [comment]
@gluap That seems to have done the trick for that issue.

Now I get this:
```
homeassistant_1  | 2020-08-22 17:33:16 ERROR (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] '01'
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 595, in run
homeassistant_1  |     self.process_message(in_data)
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 227, in process_message
homeassistant_1  |     self.duofern_parser.parse(message)
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py", line 567, in parse
homeassistant_1  |     if (sensorMsg[id][chan] == 5):
homeassistant_1  | KeyError: '01'
homeassistant_1  | 2020-08-22 17:34:00 ERROR (Thread-4) [/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py] '01'
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 595, in run
homeassistant_1  |     self.process_message(in_data)
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 227, in process_message
homeassistant_1  |     self.duofern_parser.parse(message)
homeassistant_1  |   File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py", line 567, in parse
homeassistant_1  |     if (sensorMsg[id][chan] == 5):
homeassistant_1  | KeyError: '01'
```

**Comment by gluap** [comment]
I have hopefully fixed that one as well, this time I'd suggest installing the version from a wheel (unzip first, then install using pip from the homeassistant environment to install that file. If you use hass.io or similar I don't have a lot of experience how we can get in a wheel "from the side"). If you have experience with python development (or feel adventurous) you could also do a setup .py develop of a git pull of the https://github.com/gluap/pyduofern/tree/feature/smokedetector branch in your homeassistant python virtual environment.

Here's the zipped wheel (github doesn't permit uploading wheels directly) [pyduofern-0.32.0-py3-none-any.whl.zip](https://github.com/gluap/pyduofern/files/5112775/pyduofern-0.32.0-py3-none-any.whl.zip)

Be aware that even once this issue is fixed, the the smoke detector won't immediately appear in homeassistant. The reason is that for every device type the possible actions etc... have to be put into code similar to this: https://github.com/gluap/pyduofern/blob/master/examples/homeassistant/custom_components/duofern/light.py

Which I didn't do yet for the smoke detectors. But if it were running you would at least be able to use your other devices (well, the ones that are implemented...), and probably we would see how we could sensibly implement the component (without a detector It would have been a bit hard to reverse-engineer.)

**Comment by DomiStyle** [comment]
@gluap Thanks, going to check it out once I get some spare time.

I use everything with Docker so adding a dependency for a custom component is a pain but I'm sure I can mount it somehow.

Adding the smoke detector into Home Assistant should be pretty straightforward since it only needs an alarm switch and a battery indicator.

I didn't get a chance to log the battery report (which should happen every 24h) yet though. Do I need to enable debug logging in pyduofern or should it show up on its own?

**Comment by DomiStyle** [comment]
@gluap Looks good, no error messages.

**Comment by DomiStyle** [comment]
I was able to get the smoke detector added as binary sensor in Home Assistant.

@gluap Is HA only polling from pyduofern or can I actually push data to HA when it arrives? I would be worried about an alarm being missed if HA only uses polling.
